version: '3.8'
services:
  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sonda_db
    ports:
      - '5432:5432'